language: node_js
node_js:
- "stable"

services:
- mongodb
- redis-server

script:
- "npm run test-ci"

after_script: "npm install coveralls@2.10.0 && npm audit fix --force && cat ./coverage/lcov.info | coveralls"